use std::path::Path;

use surrealkv::{LSMIterator, Mode, TreeBuilder};

use crate::HybridSpatioTemporalIndexer;

type BoxError = Box<dyn std::error::Error + Send + Sync + 'static>;

/// A decoded observation returned by spatial queries.
#[derive(Debug, Clone)]
pub struct Observation {
    pub key: Vec<u8>,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub timestamp_secs: u64,
    pub timestamp_nanos: u64,
    /// Raw serialized payload (caller interprets, e.g. as a proto Any).
    pub payload: Vec<u8>,
}

/// Persistent spatio-temporal store backed by SurrealKV.
///
/// Keys are 20-byte Morton-coded spatio-temporal indices generated by
/// [`HybridSpatioTemporalIndexer`].  Values are raw bytes so the store
/// stays codec-agnostic.
pub struct SpatioTemporalStore {
    indexer: HybridSpatioTemporalIndexer,
    tree: surrealkv::Tree,
}

impl SpatioTemporalStore {
    /// Open (or create) a store at `path` with the given indexer parameters.
    pub fn open(
        path: impl AsRef<Path>,
        max_range: f64,
        epoch_duration: u32,
    ) -> Result<Self, BoxError> {
        let tree = TreeBuilder::new()
            .with_path(path.as_ref().to_path_buf())
            .build()?;
        Ok(Self {
            indexer: HybridSpatioTemporalIndexer::new(max_range, epoch_duration),
            tree,
        })
    }

    /// Write many records in a single transaction.
    ///
    /// Each record carries its own payload. Returns the generated keys in the
    /// same order as `records`.
    pub async fn store_batch(
        &self,
        records: &[(f64, f64, f64, u64, u64, &[u8])], // (x, y, z, secs, nanos, payload)
    ) -> Result<Vec<[u8; 20]>, BoxError> {
        let mut txn = self.tree.begin()?;
        let mut keys = Vec::with_capacity(records.len());
        for &(x, y, z, secs, nanos, payload) in records {
            let key = self.indexer.generate_key(x, y, z, secs, nanos);
            txn.set(&key, payload)?;
            keys.push(key);
        }
        txn.commit().await?;
        Ok(keys)
    }

    /// Store a payload at a 4-D spatio-temporal point.
    ///
    /// Returns the 20-byte key that was written.
    pub async fn store(
        &self,
        x: f64,
        y: f64,
        z: f64,
        timestamp_secs: u64,
        timestamp_nanos: u64,
        payload: &[u8],
    ) -> Result<[u8; 20], BoxError> {
        let key = self.indexer.generate_key(x, y, z, timestamp_secs, timestamp_nanos);
        let mut txn = self.tree.begin()?;
        txn.set(&key, payload)?;
        txn.commit().await?;
        Ok(key)
    }

    /// Return all observations within a sphere that fall in the epoch
    /// containing `timestamp_secs`.
    ///
    /// No per-second time pinning: every record in the epoch that passes the
    /// sphere test is returned.
    pub fn query_epoch(
        &self,
        center_x: f64,
        center_y: f64,
        center_z: f64,
        radius: f64,
        timestamp_secs: u64,
    ) -> Result<Vec<Observation>, BoxError> {
        let depth = self.indexer.calculate_optimal_depth(radius);
        let ranges = self.indexer.get_boundary_protected_ranges(
            center_x, center_y, center_z, radius, timestamp_secs, depth,
        );
        self.collect(&ranges, center_x, center_y, center_z, radius, 0, u64::MAX)
    }

    /// Return all observations within a sphere across `[start_secs, end_secs]`.
    pub fn query_window(
        &self,
        center_x: f64,
        center_y: f64,
        center_z: f64,
        radius: f64,
        start_secs: u64,
        end_secs: u64,
    ) -> Result<Vec<Observation>, BoxError> {
        let depth = self.indexer.calculate_optimal_depth(radius);
        let ranges = self.indexer.get_boundary_protected_ranges_time_window(
            center_x, center_y, center_z, radius, start_secs, end_secs, depth,
        );
        self.collect(&ranges, center_x, center_y, center_z, radius, start_secs, end_secs)
    }

    /// Core scan: iterate KV ranges, apply exact time + sphere filters,
    /// sort chronologically.
    fn collect(
        &self,
        ranges: &[([u8; 20], [u8; 20])],
        cx: f64,
        cy: f64,
        cz: f64,
        radius: f64,
        start_secs: u64,
        end_secs: u64,
    ) -> Result<Vec<Observation>, BoxError> {
        let r2 = radius * radius;
        let mut all: Vec<Observation> = Vec::new();
        let txn = self.tree.begin_with_mode(Mode::ReadOnly)?;

        for (start, end) in ranges {
            // SurrealKV range is [start, end).  Pad end with 0x00 to make the
            // inclusive 20-byte end key exclusive: no real key is 21 bytes.
            let mut end_excl = [0u8; 21];
            end_excl[..20].copy_from_slice(end);

            let mut iter = txn.range(start.as_slice(), end_excl.as_slice())?;
            iter.seek_first()?;

            while iter.valid() {
                let key = iter.key().user_key().to_vec();
                let payload = iter.value()?;

                if let Ok(key_arr) = <[u8; 20]>::try_from(key.as_slice()) {
                    let (x, y, z, secs, nanos) = self.indexer.decode_key(&key_arr);
                    // Exact time filter: interior Morton cells aren't time-clamped
                    // by the key range; only boundary cells are.
                    let in_time = secs >= start_secs && secs <= end_secs;
                    // Exact sphere filter: Morton ranges cover the bounding box,
                    // not the sphere itself.
                    let in_sphere = {
                        let (dx, dy, dz) = (x - cx, y - cy, z - cz);
                        dx * dx + dy * dy + dz * dz <= r2
                    };
                    if in_time && in_sphere {
                        all.push(Observation { key, x, y, z, timestamp_secs: secs, timestamp_nanos: nanos, payload });
                    }
                }

                iter.next()?;
            }
        }

        // Chronological order for replay or Kalman integration.
        all.sort_by(|a, b| {
            a.timestamp_secs
                .cmp(&b.timestamp_secs)
                .then(a.timestamp_nanos.cmp(&b.timestamp_nanos))
        });

        Ok(all)
    }
}
